pipeline {

    environment{
      REGISTRY = "raniamidaoui"
      IMAGE_NAME= "gomart-authentication-service"
      IMAGE_TEST= "authentication-service-test"
      IMAGE_VERSION = "latest"
      LOGIN=credentials("sonar_login")
      NETWORK="tools_jenkins"
      SONARQUBE_URL="http://sonarqube:9000"
      PROJECT_KEY="gomart-microservice"
      REGISTRY_CRED = 'docker_creds'
    }

    agent any
    
    stages {

        
        stage('SonarTests') {
            steps{
                script{
                    docker.image('sonarsource/sonar-scanner-cli').inside('-v /var/run/docker.sock:/var/run/docker.sock --entrypoint="" --net ${NETWORK}') {
                        sh "/opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.sources=. -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${LOGIN}"
                    }
                }
            }
        }


        stage('Test') {
            steps {
                echo "Unit testing"
                sh "docker build --target test -t ${IMAGE_TEST} ."
            }
            post{
                success{
                    echo "Unit Testing Passed"
                }
                failure{
                    echo "Unit Testing Failed"
                }
            }
        }


        stage("Build"){
            steps {
                echo "Docker Build"
                script{
                    dockerImg = docker.build("${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}", ".") 
                }
            }
            post{
                success{
                    echo "Build Successful"
                }
                failure{
                    echo "Build Failed"
                }
            }
        }
         
        stage("Push"){
            steps{
                script{
                    docker.withRegistry('', "${REGISTRY_CRED}") {
                        dockerImg.push()
                    }
                }
            }
            post{
                    success{
                        echo "Push Successful"
                    }
                    failure{
                        echo "Push Failed"
                    }
            }
        }
    }


    post { 
        always { 
            sh "docker rmi authentication-service-test"
            cleanWs()
        }
    }
}